
import java.awt.Color;
import javax.swing.JOptionPane;


public class Screen1 extends javax.swing.JFrame {
String error_message = "Introduzca un valor valido (Numerico)";
    /**
     * Creates new form Screen1
     */
    public Screen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txf_distance1 = new javax.swing.JTextField();
        txf_time1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txf_speed2 = new javax.swing.JTextField();
        txf_time2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txf_distance3 = new javax.swing.JTextField();
        txf_speed3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_problem1 = new javax.swing.JButton();
        btn_problem2 = new javax.swing.JButton();
        btn_problem3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("---");

        jLabel3.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("V =");

        txf_distance1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_distance1.setToolTipText("Distancia");
        txf_distance1.setName(""); // NOI18N
        txf_distance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_distance1ActionPerformed(evt);
            }
        });

        txf_time1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_time1.setToolTipText("Tiempo");

        jLabel11.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("D =");

        txf_speed2.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_speed2.setToolTipText("Velocidad");
        txf_speed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_speed2ActionPerformed(evt);
            }
        });

        txf_time2.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_time2.setToolTipText("Tiempo");
        txf_time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_time2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("T =");

        jLabel10.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("---");

        txf_distance3.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_distance3.setToolTipText("Distancia");
        txf_distance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_distance3ActionPerformed(evt);
            }
        });

        txf_speed3.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_speed3.setToolTipText("Velocidad");
        txf_speed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_speed3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("T = Tiempo");

        jLabel6.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("D = Distancia");

        jLabel4.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("V = Velocidad");

        jLabel1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tema: Movimiento Rectilineo Uniforme");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_problem1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        btn_problem1.setText("Calcular");
        btn_problem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_problem1MouseClicked(evt);
            }
        });
        btn_problem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_problem1ActionPerformed(evt);
            }
        });

        btn_problem2.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        btn_problem2.setText("Calcular");
        btn_problem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_problem2MouseClicked(evt);
            }
        });
        btn_problem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_problem2ActionPerformed(evt);
            }
        });

        btn_problem3.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        btn_problem3.setText("Calcular");
        btn_problem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_problem3MouseClicked(evt);
            }
        });
        btn_problem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_problem3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("x");

        jButton1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jButton1.setText("<");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_speed3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_distance3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_problem1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_problem2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148)
                        .addComponent(btn_problem3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_time1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_distance1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_speed2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_problem1)
                    .addComponent(btn_problem2)
                    .addComponent(btn_problem3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txf_distance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txf_distance3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_speed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_speed3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        txf_distance1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_distance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_distance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_distance1ActionPerformed

    private void txf_speed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_speed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_speed2ActionPerformed

    private void txf_time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_time2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_time2ActionPerformed

    private void txf_distance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_distance3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_distance3ActionPerformed

    private void txf_speed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_speed3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_speed3ActionPerformed

    private void btn_problem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_problem1MouseClicked
        // TODO add your handling code here:
        String get_distance, get_time;
        get_distance = txf_distance1.getText();
        get_time = txf_time1.getText();
        
        Double d = null, t = null;
        
        if (ValidNumber(get_distance)) { // evaluar distancia
            d = Double.valueOf(get_distance);
            txf_distance1.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_distance1.setBackground(Color.red);
        }
        
        if (ValidNumber(get_time)) { // evaluar tiempo
            t = Double.valueOf(get_time);
            txf_time1.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_time1.setBackground(Color.red);
        }
        
        

        if (ValidNumber(get_distance) && ValidNumber(get_time)) {
            Double v = d/t;
            JOptionPane.showMessageDialog(this,"La velocidad es: "+String.format("%.2f", v)+"m/s");
        }
    }//GEN-LAST:event_btn_problem1MouseClicked

    private void btn_problem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_problem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_problem1ActionPerformed

    private void btn_problem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_problem2MouseClicked
        // TODO add your handling code here:
        String get_speed, get_time;
        get_speed = txf_speed2.getText();
        get_time = txf_time2.getText();
        
        Double v = null, t = null;
        
        if (ValidNumber(get_speed)) { // evaluar velocidad
            v = Double.valueOf(get_speed);
            txf_speed2.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_speed2.setBackground(Color.red);
        }
        
        if (ValidNumber(get_time)) { // evaluar tiempo
            t = Double.valueOf(get_time);
            txf_time2.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_time2.setBackground(Color.red);
        }

        if (ValidNumber(get_speed) && ValidNumber(get_time)) {
            Double d = v*t;
            JOptionPane.showMessageDialog(this,"La distancia es: "+String.format("%.2f", d)+"m");
        }
    }//GEN-LAST:event_btn_problem2MouseClicked

    private void btn_problem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_problem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_problem2ActionPerformed

    private void btn_problem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_problem3MouseClicked
        // TODO add your handling code here:
        String get_distance, get_speed;
        get_distance = txf_distance3.getText();
        get_speed = txf_speed3.getText();
        
        Double d = null, v = null;
        
        if (ValidNumber(get_distance)) { // evaluar distancia
            d = Double.valueOf(get_distance);
            txf_distance3.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_distance3.setBackground(Color.red);
        }
        
        if (ValidNumber(get_speed)) { // evaluar velocidad
            v = Double.valueOf(get_speed);
            txf_speed3.setBackground(Color.white);
        } else {
            JOptionPane.showMessageDialog(this,error_message);
            txf_speed3.setBackground(Color.red);
        }

        if (ValidNumber(get_distance) && ValidNumber(get_speed)) {
            Double t = d/v;
            JOptionPane.showMessageDialog(this,"El tiempo es: "+String.format("%.2f", t)+"s");
        }
    }//GEN-LAST:event_btn_problem3MouseClicked

    private void btn_problem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_problem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_problem3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        MainMenu connect = new MainMenu();
        connect.setVisible(true);
        connect.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen1().setVisible(true);
            }
        });
    }
    
    public boolean ValidNumber(String string) {
        boolean r;
        try {
            Double.parseDouble(string);
            r = true;
        } catch (NumberFormatException excepcion) {
            r = false;
        }
        
        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_problem1;
    private javax.swing.JButton btn_problem2;
    private javax.swing.JButton btn_problem3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txf_distance1;
    private javax.swing.JTextField txf_distance3;
    private javax.swing.JTextField txf_speed2;
    private javax.swing.JTextField txf_speed3;
    private javax.swing.JTextField txf_time1;
    private javax.swing.JTextField txf_time2;
    // End of variables declaration//GEN-END:variables
}
