
import java.awt.Color;
import javax.swing.JOptionPane;


public class Screen1_2 extends javax.swing.JFrame {
String error_message1 = "Introduzca un valor valido. (Numerico)";
String error_message2 = "Se necesitan por lo menos 2 numeros para operar.";
String error_message3 = "Un campo debe estar vacio para operar.";
    /**
     * Creates new form Screen1_2
     */
    public Screen1_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txf_distance = new javax.swing.JTextField();
        txf_speed = new javax.swing.JTextField();
        txf_time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_problem1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jButton1.setText("<");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tema: Movimiento Rectilineo Uniforme");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tiempo [t]");

        jLabel5.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Distancia [d]");

        txf_distance.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_distance.setToolTipText("Distancia (m)");
        txf_distance.setName(""); // NOI18N
        txf_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_distanceActionPerformed(evt);
            }
        });

        txf_speed.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_speed.setToolTipText("Velocidad (m/s)");
        txf_speed.setName(""); // NOI18N
        txf_speed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_speedActionPerformed(evt);
            }
        });

        txf_time.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        txf_time.setToolTipText("Tiempo (s)");
        txf_time.setName(""); // NOI18N
        txf_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_timeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Velocidad [v]");

        btn_problem1.setFont(new java.awt.Font("Minecraftia", 0, 12)); // NOI18N
        btn_problem1.setText("Calcular");
        btn_problem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_problem1MouseClicked(evt);
            }
        });
        btn_problem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_problem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txf_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_time, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_problem1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txf_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_problem1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        MainMenu connect = new MainMenu();
        connect.setVisible(true);
        connect.setLocationRelativeTo(null);
        hide();
    }//GEN-LAST:event_jButton1MouseClicked

    private void txf_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_distanceActionPerformed

    private void txf_speedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_speedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_speedActionPerformed

    private void txf_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_timeActionPerformed

    private void btn_problem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_problem1MouseClicked
        // TODO add your handling code here:
        String get_distance, get_speed, get_time;
        get_distance = txf_distance.getText();
        get_speed = txf_speed.getText();
        get_time = txf_time.getText();
        
        //System.out.println(get_distance+" a ");
        
        if (!get_distance.equals("") && !get_time.equals("") && get_speed.equals("")) { // formula para velocidad
            System.out.println("caso 1");
            Operate(1, get_distance, get_speed, get_time);
        } else if (!get_distance.equals("") && !get_speed.equals("") && get_time.equals("")) { // formula para tiempo
            System.out.println("caso 2");
            Operate(2, get_distance, get_speed, get_time);
        } else if (!get_speed.equals("") && !get_time.equals("") && get_distance.equals("")) { // formula para distancia
            System.out.println("caso 3");
            Operate(3, get_distance, get_speed, get_time);
        } else if (!get_distance.equals("") && get_speed.equals("") && get_time.equals("") ||
                get_distance.equals("") && !get_speed.equals("") && get_time.equals("") ||
                get_distance.equals("") && get_speed.equals("") && !get_time.equals("")) {
            System.out.println("caso 4 error 2");
            Operate(4, get_distance, get_speed, get_time);
        } else if (!get_distance.equals("") && !get_speed.equals("") && !get_time.equals("")) {
            System.out.println("caso 5 error 3");
            Operate(5, get_distance, get_speed, get_time);
        } else {
            System.out.println("caso no reconocido");
            Operate(0, get_distance, get_speed, get_time);
        }
        
    }//GEN-LAST:event_btn_problem1MouseClicked

    private void btn_problem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_problem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_problem1ActionPerformed

    public void Operate(int caso, String get_d, String get_v, String get_t) {
        Double d = null, v = null, t = null;
        
        switch(caso) {
            case 1:
                if (ValidNumber(get_d)) { // evaluar distancia
                    d = Double.valueOf(get_d);
                    txf_distance.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_distance.setBackground(Color.red);
                }
                if (ValidNumber(get_t)) { // evaluar tiempo
                    t = Double.valueOf(get_t);
                    txf_time.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_time.setBackground(Color.red);
                }
                
                if (ValidNumber(get_d) && ValidNumber(get_t)) {
                    v = d/t;
                    //String str_v = v+"";
                    txf_speed.setText(String.format("%.2f", v));
                }
                break;
            case 2:
                if (ValidNumber(get_d)) { // evaluar distancia
                    d = Double.valueOf(get_d);
                    txf_distance.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_distance.setBackground(Color.red);
                }
                if (ValidNumber(get_v)) { // evaluar tiempo
                    v = Double.valueOf(get_v);
                    txf_speed.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_speed.setBackground(Color.red);
                }
                
                if (ValidNumber(get_d) && ValidNumber(get_v)) {
                    t = d/v;
                    //String str_v = v+"";
                    txf_time.setText(String.format("%.2f", t));
                }
                break;
            case 3:
                if (ValidNumber(get_v)) { // evaluar distancia
                    v = Double.valueOf(get_v);
                    txf_speed.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_speed.setBackground(Color.red);
                }
                if (ValidNumber(get_t)) { // evaluar tiempo
                    t = Double.valueOf(get_t);
                    txf_time.setBackground(Color.white);
                } else {
                    JOptionPane.showMessageDialog(this,error_message1);
                    txf_time.setBackground(Color.red);
                }
                
                if (ValidNumber(get_v) && ValidNumber(get_t)) {
                    d = v*t;
                    //String str_v = v+"";
                    txf_distance.setText(String.format("%.2f", d));
                }
                break;
            case 4:
                JOptionPane.showMessageDialog(this,error_message2);
                break;
            case 5:
                JOptionPane.showMessageDialog(this,error_message3);
                break;
            case 0:
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen1_2().setVisible(true);
            }
        });
    }
    
    public boolean ValidNumber(String string) {
        boolean r;
        try {
            Double.parseDouble(string);
            r = true;
        } catch (NumberFormatException excepcion) {
            r = false;
        }
        
        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_problem1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txf_distance;
    private javax.swing.JTextField txf_speed;
    private javax.swing.JTextField txf_time;
    // End of variables declaration//GEN-END:variables
}
